{"name": "Проверка получения ошибки при повторном использовании логина, пароля и имени для создания курьера", "status": "passed", "description": "Проверяются код и тело ответа.", "start": 1742146691471, "stop": 1742146691835, "uuid": "cf0cfde5-2e3c-4d8f-8a5c-02b438595e71", "historyId": "a50dffb96edaa7b41cee6ef11f297095", "testCaseId": "a50dffb96edaa7b41cee6ef11f297095", "fullName": "tests.test_courier_create_acc.TestCourierCreate#test_create_courier_account_login_taken_conflict", "labels": [{"name": "story", "value": "Создание курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_create_acc"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "LAPTOP-NKNS1O71"}, {"name": "thread", "value": "17732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_create_acc"}]}